name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      cheat: ${{ steps.filter.outputs.cheat }}
      loader: ${{ steps.filter.outputs.loader }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            cheat:
              - 'cheat/**'
            loader:
              - 'loader/**'

  build-cheat:
    needs: detect-changes
    if: needs.detect-changes.outputs.cheat == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    name: Build Cheat DLL
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Visual Studio Components
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "[17.0,18.0)"
          vs-prerelease: false
          msbuild-architecture: x64

      - name: Build Cheat DLL
        run: msbuild /m /p:Configuration=Release ./cheat

      - name: Upload Cheat DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheat-dll
          path: cheat/x64/Release/cheat.dll

  build-loader:
    needs: detect-changes
    if: needs.detect-changes.outputs.loader == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    name: Build Tauri Loader
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: loader
        run: bun install

      - name: Build Tauri App
        working-directory: loader
        run: bun run tauri build

      - name: Upload Tauri Executable
        uses: actions/upload-artifact@v4
        with:
          name: tauri-loader
          path: loader/src-tauri/target/release/*.exe
