name: MSBuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SOLUTION_FILE_PATH: ./cheat
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Visual Studio Components
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "[17.0,18.0)"
          vs-prerelease: false
          msbuild-architecture: x64

      - name: Build
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        continue-on-error: false

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ github.sha }}
          path: ./cheat/x64/Release/**
          if-no-files-found: error
          compression-level: 9
          retention-days: 5
