name: Production CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Restore cache
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./website/node_modules
            ./website/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}

      - name: Install dependencies
        if: steps.cache-dependencies.cache-hit != 'true'
        run: cd website && bun install --frozen-lockfile

      - name: Build website
        run: cd website && bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: website/dist

  deploy:
    needs: ci
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
