name: Production CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./web
        run: bun install --frozen-lockfile

      - name: Run tests
        working-directory: ./web
        run: bun test

      - name: Build website
        working-directory: ./web
        run: bun run build

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest
    environment: Production
    needs: build-website

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/sipacid/asthmaphobia-v2-web:main 
            docker stop asthmaphobia-web || true 
            docker rm asthmaphobia-web || true 
            docker run -d -p 0.0.0.0:3004:3000 --restart unless-stopped --name asthmaphobia-web \
            --network asthmaphobia_default \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e GOOGLE_PROJECT_ID="${{ secrets.GOOGLE_PROJECT_ID }}" \
            -e GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
            -e PUBLIC_RECAPTCHA_SITE_KEY="${{ secrets.PUBLIC_RECAPTCHA_SITE_KEY }}" \
            -e RECAPTCHA_SECRET_KEY="${{ secrets.RECAPTCHA_SECRET_KEY }}" \
            ghcr.io/sipacid/asthmaphobia-v2-web:main
